### ISSUE TITLE
chore: Github Projects 칸반 보드 세팅

### ISSUE THREAD

**Issue by hoduulmu** [hhPlusDeliverySystem/delivery_system#13]
#### Description
칸반 보드 세팅

#### TODO
* [x] 이슈 등록 시 프로젝트 칸반 보드 등록
* [ ] PR 시 On Review 로 자동 이동
* [x] 머지시 Done으로 자동 이동

**Comment by hoduulmu** [comment]
자동 이동 워크플로 수가 가득 찼다고 하면서 안되기 때문에 PR시 On_Review로 이동은 안될듯 합니다
