### ISSUE TITLE
feature: DB 연결

### ISSUE THREAD

**Issue by pyuseon** [hhPlusDeliverySystem/delivery_system#6]
#### Description
데이터 베이스 연결하기

#### TODO
* [ ] CI/CD 구축을 위한 데이터 베이스 연결하기 
* [ ] Mysql 사용

#### ETC
기타

**Comment by hoduulmu** [comment]
* [x] Local Mysql 구축
* [x] Mysql 세팅 추가
