### ISSUE TITLE
study: CI/CD 스터디

### ISSUE THREAD

**Issue by pyuseon** [hhPlusDeliverySystem/delivery_system#7]
#### Description 
CI / CD에 대해 스터디하기 
#### Todo
- [ ] - dev/prod 별 빌드정책을 공부
- [ ]  소스맵, 빌드시 타입정보의 저장 등을 고려합니다.
- [ ] 배포 파이프라인 및 정책을 문서화예시 찾기.
- [ ]  서버를 배포하는 Dockerfile
- [ ] 각 phase(dev, cbt, prod)에 맞는 github actions workflow yaml 파일 github 주소
- [ ] 과제미션 : commit / push 할 때 마다 docker
- [ ] build 속도 개선한 과정 문서로 기록하여 제출 (모든 소요시간 기록)
- [ ] github acition 공부 
- [ ] docker 공부 
- [ ] ci 란? cd 란?
- [ ] 무중단 배포의 종류는?

**Comment by hoduulmu** [comment]
진행 방법이 변경됨에 따라 닫도록 하겠습니다
